global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "lancamento-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["lancamento-api:80"]

  - job_name: "consolidado-diario"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["consolidado-diario:80"]
